server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  snowflake:
    machine_id: 1
data:
  database:
    driver: mysql
    user: root
    password: "920312"
    host: 127.0.0.1:3306
    schema: geek
    max_open_conns: 30
    max_idle_conns: 30
    conn_max_life_time: 60
    debug: true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
